### ISSUE TITLE
Error outputting undefined in front matter

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-to-hugo#137]
### Steps to Reproduce

You can see this converting `sts-471j-engineering-apollo-the-moon-project-as-a-complex-system-spring-2007`

### Stacktrace

    YAMLException: unacceptable kind of an object to dump [object Undefined]
        at writeNode (/home/george/Projects/ocw-to-hugo/node_modules/js-yaml/lib/js-yaml/dumper.js:756:13)
        at writeBlockMapping (/home/george/Projects/ocw-to-hugo/node_modules/js-yaml/lib/js-yaml/dumper.js:634:10)
        at writeNode (/home/george/Projects/ocw-to-hugo/node_modules/js-yaml/lib/js-yaml/dumper.js:727:9)
        at dump (/home/george/Projects/ocw-to-hugo/node_modules/js-yaml/lib/js-yaml/dumper.js:817:7)
        at Object.safeDump (/home/george/Projects/ocw-to-hugo/node_modules/js-yaml/lib/js-yaml/dumper.js:823:10)
        at generatePdfMarkdown (/home/george/Projects/ocw-to-hugo/src/markdown_generators.js:367:23)
        at /home/george/Projects/ocw-to-hugo/src/markdown_generators.js:122:21
        at Array.map (<anonymous>)
        at generateMarkdownRecursive (/home/george/Projects/ocw-to-hugo/src/markdown_generators.js:114:8)
        at Object.<anonymous> (/home/george/Projects/ocw-to-hugo/src/markdown_generators.js:45:15) {
      reason: 'unacceptable kind of an object to dump [object Undefined]',
      mark: undefined,
      level: 'error',
      service: 'user-service',
      [Symbol(level)]: 'error',
      [Symbol(message)]: '{"name":"YAMLException","reason":"unacceptable kind of an object to dump [object Undefined]","message":"unacceptable kind of an object to dump [object Undefined]","level":"error","'
    }

**Comment by noisecapella** [comment]
Here's the total list of courses which are published but had this problem:

    "11-943j-urban-transportation-land-use-and-the-environment-spring-2002",
    "16-885j-aircraft-systems-engineering-fall-2004"
    "16-891j-space-policy-seminar-spring-2003",
    "18-024-multivariable-calculus-with-theory-spring-2011"
    "21m-380-music-and-technology-sound-design-spring-2016",
    "res-18-001-calculus-online-textbook-spring-2005"
    "res-18-006-calculus-revisited-single-variable-calculus-fall-2010",
    "sts-003-the-rise-of-modern-science-fall-2010"
    "sts-471j-engineering-apollo-the-moon-project-as-a-complex-system-spring-2007",

There's an issue linking PDFs which could be causing this issue for some of these courses: https://github.com/mitodl/hugo-course-publisher/issues/422
