### ISSUE TITLE
Quote processing breaks on a course

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-to-hugo#177]
### Steps to Reproduce

Convert `18-05-introduction-to-probability-and-statistics-spring-2014` and have `--verbose` set so you can see errors.

### Stacktrace

    ➜  ocw-to-hugo git:(master) ✗ time ./src/bin/index.js -i ../ocw-data-parser/parsed_courses -o ./private/output -c ../ocw-data-parser/example_courses.json --verbose
    Converting 1 courses to Hugo markdown...
     ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0% | ETA: 0s | 0/1course 18-05-introduction-to-probability-and-statistics-spring-2014
     ████████████████████████████████████████ 100% | ETA: 0s | 1/1
    Found errors which were logged:  [
      TypeError: Cannot read property 'textContent' of undefined
          at Object.replacement (/home/george/Projects/ocw-to-hugo/src/turndown.js:262:55)
          at TurndownService.replacementForNode (/home/george/Projects/ocw-to-hugo/node_modules/turndown/lib/turndown.cjs.js:877:10)
          at /home/george/Projects/ocw-to-hugo/node_modules/turndown/lib/turndown.cjs.js:836:40
          at NodeList.reduce (<anonymous>)
          at TurndownService.process (/home/george/Projects/ocw-to-hugo/node_modules/turndown/lib/turndown.cjs.js:829:17)
          at TurndownService.replacementForNode (/home/george/Projects/ocw-to-hugo/node_modules/turndown/lib/turndown.cjs.js:872:25)
          at /home/george/Projects/ocw-to-hugo/node_modules/turndown/lib/turndown.cjs.js:836:40
          at NodeList.reduce (<anonymous>)
          at TurndownService.process (/home/george/Projects/ocw-to-hugo/node_modules/turndown/lib/turndown.cjs.js:829:17)
          at TurndownService.replacementForNode (/home/george/Projects/ocw-to-hugo/node_modules/turndown/lib/turndown.cjs.js:872:25) {
        level: 'error',
        service: 'user-service',
        [Symbol(level)]: 'error',
        [Symbol(message)]: '{"level":"error","service":"user-service"}'
      }
    ]
    ./src/bin/index.js -i ../ocw-data-parser/parsed_courses -o ./private/output -  1.42s user 0.10s system 142% cpu 1.069 total

**Comment by pdpinch** [comment]
@noisecapella @gumaerc is this still an issue?

**Comment by noisecapella** [comment]
Yes, still get the same exception
