### ISSUE TITLE
non-zero exit code with no error message

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-to-hugo#268]
### Steps to Reproduce

Manually edit the `index.js` `run` function and add in a line to intentionally throw an error like so:

`throw new Error("test error")`

### Expected Behavior

The error should be displayed in the console regardless of the `--verbose` flag, but not with the other mess of errors thrown by Turndown, etc.

### Actual Behavior

`ocw-to-hugo` exits with error code 1 but does not display anything in the console.

### Additional Info

The `--verbose` flag was added due to the nature of converting all 2500+ OCW courses being very error prone and noisy.  Instead of spitting out all the errors, the errors are logged to `ocw-to-hugo.error.log` with Winston.  When errors are caught in the `.catch` function attached to `run` in `index.js`, both `console.error` and `loggers.fileLogger.error` are called, but no error is logged to the console and it seems a blank error is deposited in the file.  Most (if not all) Turndown errors should be caught and logged before reaching this catch block, so any errors actually caught in this block should bypass the `--verbose` flag and be displayed to console.

**Comment by noisecapella** [comment]
I edited `index.js` to be:

    const run = async () => {
      throw new Error("test error")
      if (options.courses && options.download) {
        await downloadCourses(options.courses, options.input)
      } else if (options.download && !options.courses) {
        throw new Error(MISSING_JSON_ERROR_MESSAGE)
      }
      if (options.rm) {
        console.log(`Removing the contents of ${options.output}...`)
        await rmdir(options.output, { recursive: true })
        await mkdir(options.output)
      }
      await scanCourses(options.input, options.output)
    }

My output:

    ➜  ocw-to-hugo git:(release) ✗ time ./src/bin/index.js -i ../ocw-data-parser/parsed_courses -o ./private/pr
    Error: Error: test error
        at run (/home/george/Projects/ocw-to-hugo/src/bin/index.js:69:9)
        at Object.<anonymous> (/home/george/Projects/ocw-to-hugo/src/bin/index.js:83:1)
        at Module._compile (internal/modules/cjs/loader.js:1063:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        at Module.load (internal/modules/cjs/loader.js:928:32)
        at Function.Module._load (internal/modules/cjs/loader.js:769:14)
        at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
        at internal/main/run_main_module.js:17:47
    ./src/bin/index.js -i ../ocw-data-parser/parsed_courses -o ./private/pr  0.39s user 0.04s system 97% cpu 0.436 total
